site_name: miracle-wm wiki
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/mattkae/miracle
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting Started:
    - getting_started/installation.md
    - getting_started/building.md
    - getting_started/what_is_a_wayland_compositor.md
  - Configuration: 
    - configuration/introduction.md
    - configuration/action_key.md
    - configuration/default_keybinds.md
    - configuration/custom_actions.md
    - configuration/startup_apps.md
    - configuration/inner_gaps.md
    - configuration/outer_gaps.md
    - configuration/border.md
    - configuration/enable_animations.md
    - configuration/animations.md
    - configuration/terminal.md
    - configuration/resize_jump.md
    - configuration/environment_variables.md
    - configuration/workspaces.md
    - configuration/move_modifier.md
    - configuration/drag_and_drop.md
  - IPC:
    - ipc/index.md
    - ipc/get_workspaces.md
    - ipc/subscribe.md
    - ipc/get_outputs.md
    - ipc/get_version.md
    - ipc/get_binding_modes.md
    - Commands:
      - ipc/commands/layout_command.md
      - ipc/commands/resize_command.md
  - Display Configuration: configuration/display_configuration.md
  - Screen Sharing: screenshare.md
  - Mir's Built-in Configuration: configuration/mir.md
  - Roadmap: roadmap.md
extra:
  version:
    provider: mike
